'use client'

import { useCallback, useEffect, useState } from 'react'
import { Alert, Button, Card, Form, Input, InputNumber, Message, Modal, Popconfirm, Space, Switch, Table, Tag, Typography } from '@arco-design/web-react'
import { IconDelete, IconEdit, IconPlus, IconSave } from '@arco-design/web-react/icon'
import { cmsApi } from '@/features/admin/lib/api'
import type { FriendLink, NavigationItem } from '@/features/admin/lib/types'
import { AdminPageHeader } from './AdminPageHeader'

export function SiteSettingsView() {
  const [form] = Form.useForm();const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false)
  useEffect(()=>{cmsApi.settings().then(values=>form.setFieldsValue(values)).catch(()=>Message.error('站点设置加载失败')).finally(()=>setLoading(false))},[form])
  const save=async()=>{try{setSaving(true);const values=await form.validate();await cmsApi.updateSettings(values);Message.success('站点设置已保存')}catch{Message.error('保存失败，请检查字段')}finally{setSaving(false)}}
  return <><AdminPageHeader title="站点设置" subtitle="基础信息、首页文案、社交链接和页脚设置均保存在 SQLite" extra={<Button type="primary" icon={<IconSave/>} loading={saving} onClick={save}>保存设置</Button>} /><Card className="cot-admin-card" loading={loading}><Form form={form} layout="vertical"><Form.Item field="site.title" label="站点标题" rules={[{required:true,message:'请输入站点标题'}]}><Input maxLength={120}/></Form.Item><Form.Item field="site.description" label="站点描述"><Input.TextArea autoSize={{minRows:3}} maxLength={300}/></Form.Item><Form.Item field="site.url" label="站点域名" rules={[{type:'url',message:'请输入合法 URL'}]}><Input placeholder="https://blog.example.com"/></Form.Item><Form.Item field="site.author" label="作者名称"><Input/></Form.Item><Form.Item field="site.email" label="联系邮箱"><Input type="email"/></Form.Item><Form.Item field="presentation.hero.greeting" label="首页欢迎语"><Input/></Form.Item><Form.Item field="presentation.hero.role" label="个人角色"><Input/></Form.Item><Form.Item field="footer.icp" label="ICP备案"><Input/></Form.Item></Form></Card></>
}

export function FriendsView(){const [items,setItems]=useState<FriendLink[]>([]);const [editing,setEditing]=useState<FriendLink>();const [visible,setVisible]=useState(false);const [form]=Form.useForm();const load=useCallback(async()=>{try{setItems(await cmsApi.friends())}catch{Message.error('友链加载失败')}},[]);useEffect(()=>{void load()},[load]);const open=(item?:FriendLink)=>{setEditing(item);form.resetFields();form.setFieldsValue(item||{enabled:true,sortOrder:0});setVisible(true)};const save=async()=>{try{const values=await form.validate();if(editing)await cmsApi.updateFriend(editing.id,values);else await cmsApi.createFriend(values);Message.success('友链已保存');setVisible(false);void load()}catch{Message.error('保存失败，请检查名称和链接')}};const remove=async(item:FriendLink)=>{try{await cmsApi.deleteFriend(item.id);Message.success('友链已删除');void load()}catch{Message.error('删除失败')}};return <><AdminPageHeader title="友链" subtitle="直接管理名称、图床头像链接、描述、分组和启用状态" extra={<Button type="primary" icon={<IconPlus/>} onClick={()=>open()}>新增友链</Button>}/><Card className="cot-admin-card"><div style={{overflowX:'auto'}}><Table rowKey="id" data={items} pagination={false} columns={[{title:'名称',dataIndex:'name',render:(value,item)=><Space direction="vertical" size={2}><Typography.Text bold>{value}</Typography.Text><Typography.Text type="secondary" ellipsis={{showTooltip:true}} style={{maxWidth:240}}>{(item as FriendLink).url}</Typography.Text></Space>},{title:'分组',dataIndex:'groupName'},{title:'状态',dataIndex:'enabled',render:value=><Tag color={value?'green':'gray'}>{value?'启用':'隐藏'}</Tag>},{title:'排序',dataIndex:'sortOrder'},{title:'操作',render:(_,item)=><Space><Button type="text" icon={<IconEdit/>} onClick={()=>open(item as FriendLink)}/><Popconfirm title="删除友链" content="删除后不可恢复。" onOk={()=>remove(item as FriendLink)}><Button type="text" status="danger" icon={<IconDelete/>}/></Popconfirm></Space>}]}/></div></Card><Modal title={editing?'编辑友链':'新增友链'} visible={visible} onCancel={()=>setVisible(false)} onOk={save} okText="保存" unmountOnExit><Form form={form} layout="vertical"><Form.Item field="name" label="名称" rules={[{required:true}]}><Input/></Form.Item><Form.Item field="url" label="站点链接" rules={[{required:true,type:'url'}]}><Input placeholder="https://…"/></Form.Item><Form.Item field="avatarUrl" label="头像图床链接" rules={[{type:'url'}]}><Input placeholder="https://…"/></Form.Item><Form.Item field="description" label="描述"><Input.TextArea/></Form.Item><Form.Item field="groupName" label="分组"><Input/></Form.Item><Form.Item field="sortOrder" label="排序"><InputNumber min={0}/></Form.Item><Form.Item field="enabled" label="启用"><Switch/></Form.Item></Form></Modal></>}

export function NavigationView(){const [items,setItems]=useState<NavigationItem[]>([]);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const load=useCallback(async()=>{setLoading(true);try{setItems(await cmsApi.navigation())}catch{Message.error('导航加载失败')}finally{setLoading(false)}},[]);useEffect(()=>{void load()},[load]);const add=()=>setItems(value=>[...value,{id:`draft-${Date.now()}`,label:'新导航项',href:'/',sortOrder:value.length,enabled:true}]);const change=(id:string,key:keyof NavigationItem,value:string|number|boolean)=>setItems(current=>current.map(item=>item.id===id?{...item,[key]:value}:item));const remove=(id:string)=>setItems(current=>current.filter(item=>item.id!==id));const save=async()=>{try{setSaving(true);await cmsApi.updateNavigation(items.map(({children,...item})=>item));Message.success('导航已保存');void load()}catch{Message.error('保存失败，请检查标签与链接')}};return <><AdminPageHeader title="导航菜单" subtitle="支持添加、编辑、排序和隐藏一级导航；子菜单将在下一次迭代加入拖拽编辑" extra={<Space><Button icon={<IconPlus/>} onClick={add}>新增导航项</Button><Button type="primary" icon={<IconSave/>} loading={saving} onClick={save}>保存导航</Button></Space>}/><Card className="cot-admin-card" loading={loading}><Alert type="info" title="链接规则" content="内部链接以 / 开始；外部链接必须使用 http:// 或 https://。" style={{marginBottom:16}}/><div style={{overflowX:'auto'}}><Table rowKey="id" data={items} pagination={false} columns={[{title:'名称',render:(_,item)=><Input value={(item as NavigationItem).label} onChange={value=>change((item as NavigationItem).id,'label',value)}/>},{title:'链接',render:(_,item)=><Input value={(item as NavigationItem).href} onChange={value=>change((item as NavigationItem).id,'href',value)}/>},{title:'排序',width:120,render:(_,item)=><InputNumber min={0} value={(item as NavigationItem).sortOrder} onChange={value=>change((item as NavigationItem).id,'sortOrder',Number(value))}/>},{title:'显示',width:100,render:(_,item)=><Switch checked={(item as NavigationItem).enabled} onChange={value=>change((item as NavigationItem).id,'enabled',value)}/>},{title:'操作',width:80,render:(_,item)=><Button type="text" status="danger" icon={<IconDelete/>} onClick={()=>remove((item as NavigationItem).id)}/>}]}/></div></Card></>}
