const techStack = [
  { name: 'C', icon: '/assets/icons/tech/c.svg' },
  { name: 'Python', icon: '/assets/icons/tech/python.svg' },
  { name: 'JavaScript', icon: '/assets/icons/tech/javascript.svg' },
  { name: 'TypeScript', icon: '/assets/icons/tech/typescript.svg' },
  { name: 'HTML5', icon: '/assets/icons/tech/html5.svg' },
  { name: 'CSS', icon: '/assets/icons/tech/css.svg' },
  { name: 'Vue.js', icon: '/assets/icons/tech/vuedotjs.svg' },
  { name: 'Nuxt', icon: '/assets/icons/tech/nuxt.svg' },
  { name: 'React', icon: '/assets/icons/tech/react.svg' },
  { name: 'Next.js', icon: '/assets/icons/tech/nextdotjs.svg' },
  { name: 'Tailwind CSS', icon: '/assets/icons/tech/tailwindcss.svg' },
  { name: 'PostCSS', icon: '/assets/icons/tech/postcss.svg' },
  { name: 'Headless UI', icon: '/assets/icons/tech/headlessui.svg' },
  { name: 'Radix UI', icon: '/assets/icons/tech/radixui.svg' },
  { name: 'shadcn/ui', icon: '/assets/icons/tech/shadcnui.svg' },
  { name: 'Drizzle ORM', icon: '/assets/icons/tech/drizzle.svg' },
  { name: 'SQLite', icon: '/assets/icons/tech/sqlite.svg' },
  { name: 'Node.js', icon: '/assets/icons/tech/nodedotjs.svg' },
  { name: 'MDX', icon: '/assets/icons/tech/mdx.svg' },
  { name: 'Markdown', icon: '/assets/icons/tech/markdown.svg' },
  { name: 'pnpm', icon: '/assets/icons/tech/pnpm.svg' },
  { name: 'Git', icon: '/assets/icons/tech/git.svg' },
  { name: 'GitHub', icon: '/assets/icons/tech/github.svg' },
  { name: 'Figma', icon: '/assets/icons/tech/figma.svg' },
  { name: 'Java', icon: '/assets/icons/tech/java.svg' },
  { name: 'Go', icon: '/assets/icons/tech/go.svg' },
  { name: 'Rust', icon: '/assets/icons/tech/rust.svg' },
  { name: 'C++', icon: '/assets/icons/tech/cplusplus.svg' },
  { name: 'Docker', icon: '/assets/icons/tech/docker.svg' },
  { name: 'Nginx', icon: '/assets/icons/tech/nginx.svg' },
  { name: 'Redis', icon: '/assets/icons/tech/redis.svg' },
  { name: 'MySQL', icon: '/assets/icons/tech/mysql.svg' },
  { name: 'MongoDB', icon: '/assets/icons/tech/mongodb.svg' },
  { name: 'Spring Boot', icon: '/assets/icons/tech/springboot.svg' },
  { name: 'Angular', icon: '/assets/icons/tech/angular.svg' },
  { name: 'Svelte', icon: '/assets/icons/tech/svelte.svg' },
] as const

export default techStack
